### PR TITLE
fix #135 live update of soft version

### LINKED ISSUE #135: should auto update SoftVersion when cita bin is updated
CITA bin was v0.20.2 and  is updated with  v0.24.1, but SoftVersion is still showing as v0.20.2

Screen Shot 2019-07-19 at 7 14 46 PM

### PR DESCRIPTION
**Pull request by blankwu**
将 soft version 变量引入函数，并在每次请求时更新变量数值；

### CODE REVIEW

**Review by mfuuzy — APPROVED** [review]

**Comment by rainchen** [comment]
@blankwu please rebase, since #144

**Comment by blankwu** [comment]
> @blankwu please rebase, since #144

Done

**Comment by rainchen** [comment]
@blankwu your didn't rebase well, please update (use git up) and rebase

**Comment by blankwu** [comment]
> @blankwu your didn't rebase well, please update (use git up) and rebase

check again

**Review by rainchen — APPROVED** [review]

**Pull request merged**
