### PR TITLE
add arm64 support

### PR DESCRIPTION
**Pull request by k4nzdroid**
Add arm64 support (both the server and the agent).
Allow users to build agent images to support multiple CPU arch.

### CODE REVIEW

**Review by rainchen — CHANGES_REQUESTED** [review]
find out why CI failed

**Comment by k4nzdroid** [comment]
> find out why CI failed

**Comment by k4nzdroid** [comment]
> find out why CI failed

I'm on it.

**Comment by rainchen** [comment]
@k4nzdroid why closed this PR? Should keep using the same PR to resolve one issue.

**Comment by k4nzdroid** [comment]
@rainchen My apologies. it's a misoperation.

**Comment by k4nzdroid** [comment]
> find out why CI failed

@rainchen failed in `make code-audit`

In Makefile, the code used to match .py files for the pylint doesn't work correctly in various scenarios. 
(1) ` **/*.py`,  It's a Bash feature, called `globstar`. This makes the code is not portable.
(2) And only matching subfolder, but not recursively. Base on that, if there isn't a subfolder containing .py files, then the '**/*.py' will be passed to pylint. This is why our CI failed.
(3) Besides, codes in deeper folders will be ignored cause the lint cannot match them. 
(4) This problem also appears in yapf and shellcheck. 

So I change those codes, let them get files from the current git repo. Besides, git already knows all of the files' names, Which is faster than searching in folders.

Now, CI passed.

**Comment by rainchen** [comment]
@k4nzdroid please rebase this branch, should not include following commits:

```
bump version to v0.5.0
Merge pull request #164 from citahub/release/v0.5.0 …
```

**Review by rainchen — APPROVED** [review]

**Comment by rainchen** [comment]
@k4nzdroid thx, merged

**Pull request merged**
